Add fix for checkign PR files to code-checks

diff --git a/.github/workflows/code-checks-python.yml b/.github/workflows/code-checks-python.yml
--- a/.github/workflows/code-checks-python.yml
+++ b/.github/workflows/code-checks-python.yml
@@ -10,8 +10,25 @@ jobs:
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
-      - name: Checkout code
+      - name: Verify merge commit sha
+        id: verify_merge_commit_sha
+        run: |
+          if [ -z "${{ github.event.pull_request.merge_commit_sha }}" ]; then
+            echo "::error title=PR Commit Merge Error::The pull request does not have a merge commit SHA. Skipping the workflow. Please create a new empty commit using the --allow-empty flag and try again."
+            exit 1
+          fi
+        if: ${{ github.event_name == 'pull_request_target' }}
+      - name: Checkout PR merge commit
+        id: checkout_pr_merge_commit
         uses: actions/checkout@v4
+        with:
+          ref: "${{ github.event.pull_request.merge_commit_sha }}"
+        if: ${{ github.event_name == 'pull_request_target' }}
+      - name: Checkout branch
+        id: checkout_branch
+        uses: actions/checkout@v4
+        if: ${{ github.event_name != 'pull_request_target' }}
+
       - name: Generate matrix
         id: set-matrix
         run: |
@@ -52,8 +69,24 @@ jobs:
       fail-fast: false
       matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
     steps:
-      - name: Checkout code
+      - name: Verify merge commit sha
+        id: verify_merge_commit_sha
+        run: |
+          if [ -z "${{ github.event.pull_request.merge_commit_sha }}" ]; then
+            echo "::error title=PR Commit Merge Error::The pull request does not have a merge commit SHA. Skipping the workflow. Please create a new empty commit using the --allow-empty flag and try again."
+            exit 1
+          fi
+        if: ${{ github.event_name == 'pull_request_target' }}
+      - name: Checkout PR merge commit
+        id: checkout_pr_merge_commit
         uses: actions/checkout@v4
+        with:
+          ref: "${{ github.event.pull_request.merge_commit_sha }}"
+        if: ${{ github.event_name == 'pull_request_target' }}
+      - name: Checkout branch
+        id: checkout_branch
+        uses: actions/checkout@v4
+        if: ${{ github.event_name != 'pull_request_target' }}
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -89,8 +122,24 @@ jobs:
       fail-fast: false
       matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
     steps:
-      - name: Checkout code
+      - name: Verify merge commit sha
+        id: verify_merge_commit_sha
+        run: |
+          if [ -z "${{ github.event.pull_request.merge_commit_sha }}" ]; then
+            echo "::error title=PR Commit Merge Error::The pull request does not have a merge commit SHA. Skipping the workflow. Please create a new empty commit using the --allow-empty flag and try again."
+            exit 1
+          fi
+        if: ${{ github.event_name == 'pull_request_target' }}
+      - name: Checkout PR merge commit
+        id: checkout_pr_merge_commit
         uses: actions/checkout@v4
+        with:
+          ref: "${{ github.event.pull_request.merge_commit_sha }}"
+        if: ${{ github.event_name == 'pull_request_target' }}
+      - name: Checkout branch
+        id: checkout_branch
+        uses: actions/checkout@v4
+        if: ${{ github.event_name != 'pull_request_target' }}
 
       - name: Set up Python
         uses: actions/setup-python@v5
