Use bash for validation

diff --git a/.github/workflows/pull-validate-service-accounts.yaml b/.github/workflows/pull-validate-service-accounts.yaml
--- a/.github/workflows/pull-validate-service-accounts.yaml
+++ b/.github/workflows/pull-validate-service-accounts.yaml
@@ -2,8 +2,8 @@ name: pull-validate-service-accounts
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
-on: # runs on main
-  pull_request_target:
+on:
+  pull_request:
     types: [opened, edited, synchronize, reopened, ready_for_review]
     branches:
       - main
@@ -51,5 +51,33 @@ jobs:
       - name: Convert plan to json
         run: tofu -chdir=./configs/terraform/environments/prod show -no-color -json plan.out > plan.json
 
-      - name: Validate servcie accounts name
-        run: cat plan.json
+      - name: Validate service account names
+        run: |
+          plan_file="plan.json"
+
+          if [[ ! -f "$plan_file" ]]; then
+              echo "File not found: $plan_file"
+              exit 1
+          fi
+
+          invalid_accounts=0
+
+          while read -r account; do
+              if ! [[ $account =~ ^[a-z] ]]; then
+                  echo "Invalid name for service account: $account"
+                  invalid_accounts=$((++invalid_accounts))
+                  echo $invalid_accounts
+              fi
+          done <<<"$(jq -r '
+                       .planned_values.root_module.resources +
+                       (.planned_values.root_module.child_modules | map(.resources) | add) |
+                       .[] |
+                       select(.type == "google_service_account") |
+           .name' "$plan_file")"
+
+          if [[ $invalid_accounts -ne 0 ]]; then
+              echo "$invalid_accounts invalid service account names found."
+              exit 1
+          else
+              echo "All service account names are valid."
+          fi
