Add PR controller

diff --git a/.github/workflows/pull-go-lint.yaml b/.github/workflows/pull-go-lint.yaml
--- a/.github/workflows/pull-go-lint.yaml
+++ b/.github/workflows/pull-go-lint.yaml
@@ -1,19 +1,32 @@
 name: pull-go-lint
 
 on:
-  pull_request:
-    branches:
-      - main
-    paths:
-      - '.github/workflows/pull-go-lint.yaml'
-      - '**/*.go'
-      - '.golangci.yaml'
+  # This workflow is triggered by workflow controller.
+  workflow_call:
+    
 
 jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Verify merge commit sha
+        id: verify_merge_commit_sha
+        run: |
+          if [ -z "${{ github.event.pull_request.merge_commit_sha }}" ]; then
+            echo "::error title=PR Commit Merge Error::The pull request does not have a merge commit SHA. Skipping the workflow. Please create a new empty commit using the --allow-empty flag and try again."
+            exit 1
+          fi
+        if: ${{ github.event_name == 'pull_request_target' }}
+      - name: Checkout PR merge commit
+        id: checkout_pr_merge_commit
+        uses: actions/checkout@v4
+        with:
+          ref: "${{ github.event.pull_request.merge_commit_sha }}"
+        if: ${{ github.event_name == 'pull_request_target' }}
+      - name: Checkout branch
+        id: checkout_branch
+        uses: actions/checkout@v4
+        if: ${{ github.event_name != 'pull_request_target' }}
 
       - name: Set up Go
         uses: actions/setup-go@v5
